import type { MeasurementAsset } from "@/lib/types";

// Catálogo base importado del F-CA-37 (archivo revisado el 13/06/2025).
export const measurementAssetCatalog: MeasurementAsset[] = [
  {
    "id": "equipment-tow-ba-001",
    "code": "TOW-BA-001",
    "name": "BÁSCULA ELECTRÓNICA",
    "location": "REFACCIONES",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-06-11",
    "nextDueDate": "2025-08-10",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de masa.",
    "referenceStandardIds": [
      "standard-ohaus-5660-1",
      "standard-pe-tow-001",
      "standard-pe-tow-002",
      "standard-pe-tow-003",
      "standard-pe-tow-004",
      "standard-pe-tow-005",
      "standard-pe-tow-006",
      "standard-pe-tow-007"
    ],
    "referenceStandardId": "standard-ohaus-5660-1",
    "measurementCategory": "MASA",
    "measurementType": "PESO",
    "model": "XK3118T1",
    "serialNumber": "18070839A",
    "measurementRange": "0.00 Kg - 5 Ton",
    "resolution": "0.50 Kg",
    "observations": "OT POR NIVEL",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 7
  },
  {
    "id": "equipment-tow-ba-002",
    "code": "TOW-BA-002",
    "name": "BÁSCULA ELECTRÓNICA",
    "location": "URDIDO",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-05-23",
    "nextDueDate": "2025-07-22",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de masa.",
    "referenceStandardIds": [
      "standard-ohaus-5660-1",
      "standard-pe-tow-001",
      "standard-pe-tow-002",
      "standard-pe-tow-003",
      "standard-pe-tow-004",
      "standard-pe-tow-005",
      "standard-pe-tow-006",
      "standard-pe-tow-007"
    ],
    "referenceStandardId": "standard-ohaus-5660-1",
    "measurementCategory": "MASA",
    "measurementType": "PESO",
    "model": "ENTEC 700E",
    "serialNumber": "UG35899",
    "measurementRange": "0.00 Kg - 5 Ton",
    "resolution": "0.1 Kg",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 8
  },
  {
    "id": "equipment-tow-ba-003",
    "code": "TOW-BA-003",
    "name": "BÁSCULA ELECTRÓNICA",
    "location": "ENGOMADO wp2",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-05-27",
    "nextDueDate": "2025-07-26",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de masa.",
    "referenceStandardIds": [
      "standard-ohaus-5660-1",
      "standard-pe-tow-001",
      "standard-pe-tow-002",
      "standard-pe-tow-003",
      "standard-pe-tow-004",
      "standard-pe-tow-005",
      "standard-pe-tow-006",
      "standard-pe-tow-007"
    ],
    "referenceStandardId": "standard-ohaus-5660-1",
    "measurementCategory": "MASA",
    "measurementType": "PESO",
    "model": "P2000B",
    "serialNumber": "68002225",
    "measurementRange": "000.00 Kg - 50.00 Kg",
    "resolution": "0.01 Kg",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 9
  },
  {
    "id": "equipment-tow-ba-004",
    "code": "TOW-BA-004",
    "name": "BÁSCULA ELECTRÓNICA",
    "location": "ALMACEN",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-05-23",
    "nextDueDate": "2025-07-22",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de masa.",
    "referenceStandardIds": [
      "standard-ohaus-5660-1",
      "standard-pe-tow-001",
      "standard-pe-tow-002",
      "standard-pe-tow-003",
      "standard-pe-tow-004",
      "standard-pe-tow-005",
      "standard-pe-tow-006",
      "standard-pe-tow-007"
    ],
    "referenceStandardId": "standard-ohaus-5660-1",
    "measurementCategory": "MASA",
    "measurementType": "PESO",
    "model": "GY20002",
    "serialNumber": "",
    "measurementRange": "0.01g - 2000 g",
    "resolution": "0.0 1g",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 10
  },
  {
    "id": "equipment-tow-ba-005",
    "code": "TOW-BA-005",
    "name": "BÁSCULA ELECTRÓNICA",
    "location": "ENGOMADO WP2",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-04-07",
    "nextDueDate": "2025-06-06",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de masa.",
    "referenceStandardIds": [
      "standard-ohaus-5660-1",
      "standard-pe-tow-001",
      "standard-pe-tow-002",
      "standard-pe-tow-003",
      "standard-pe-tow-004",
      "standard-pe-tow-005",
      "standard-pe-tow-006",
      "standard-pe-tow-007"
    ],
    "referenceStandardId": "standard-ohaus-5660-1",
    "measurementCategory": "MASA",
    "measurementType": "PESO",
    "model": "LP 7513",
    "serialNumber": "SN",
    "measurementRange": "000.0 Kg - 2 Ton",
    "resolution": "000.1 Kg",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 11
  },
  {
    "id": "equipment-tow-ba-006",
    "code": "TOW-BA-006",
    "name": "BÁSCULA ELECTRÓNICA",
    "location": "TEJIDO",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-05-23",
    "nextDueDate": "2025-07-22",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de masa.",
    "referenceStandardIds": [
      "standard-ohaus-5660-1",
      "standard-pe-tow-001",
      "standard-pe-tow-002",
      "standard-pe-tow-003",
      "standard-pe-tow-004",
      "standard-pe-tow-005",
      "standard-pe-tow-006",
      "standard-pe-tow-007"
    ],
    "referenceStandardId": "standard-ohaus-5660-1",
    "measurementCategory": "MASA",
    "measurementType": "PESO",
    "model": "EXCELL BH-600",
    "serialNumber": "A053011177",
    "measurementRange": "0.00 g - 600 g",
    "resolution": "0.01 g",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 12
  },
  {
    "id": "equipment-tow-ba-007",
    "code": "TOW-BA-007",
    "name": "BÁSCULA ELECTRÓNICA",
    "location": "TEJIDO",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-05-23",
    "nextDueDate": "2025-07-22",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de masa.",
    "referenceStandardIds": [
      "standard-ohaus-5660-1",
      "standard-pe-tow-001",
      "standard-pe-tow-002",
      "standard-pe-tow-003",
      "standard-pe-tow-004",
      "standard-pe-tow-005",
      "standard-pe-tow-006",
      "standard-pe-tow-007"
    ],
    "referenceStandardId": "standard-ohaus-5660-1",
    "measurementCategory": "MASA",
    "measurementType": "PESO",
    "model": "BAPO-10",
    "serialNumber": "BAPO10-4495-0195",
    "measurementRange": "0.20 kg - 10 Kg",
    "resolution": "0.01 Kg",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 13
  },
  {
    "id": "equipment-tow-ba-008",
    "code": "TOW-BA-008",
    "name": "BÁSCULA ELECTRÓNICA",
    "location": "TEJIDO",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-05-23",
    "nextDueDate": "2025-07-22",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de masa.",
    "referenceStandardIds": [
      "standard-ohaus-5660-1",
      "standard-pe-tow-001",
      "standard-pe-tow-002",
      "standard-pe-tow-003",
      "standard-pe-tow-004",
      "standard-pe-tow-005",
      "standard-pe-tow-006",
      "standard-pe-tow-007"
    ],
    "referenceStandardId": "standard-ohaus-5660-1",
    "measurementCategory": "MASA",
    "measurementType": "PESO",
    "model": "BAPRE-3",
    "serialNumber": "BAPRE3-3272-0/89",
    "measurementRange": "0.00 Kg - 3 Kg",
    "resolution": "0.02 Kg",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 14
  },
  {
    "id": "equipment-tow-ba-009",
    "code": "TOW-BA-009",
    "name": "BÁSCULA ELECTRÓNICA",
    "location": "CRUDO",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-05-27",
    "nextDueDate": "2025-07-26",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de masa.",
    "referenceStandardIds": [
      "standard-ohaus-5660-1",
      "standard-pe-tow-001",
      "standard-pe-tow-002",
      "standard-pe-tow-003",
      "standard-pe-tow-004",
      "standard-pe-tow-005",
      "standard-pe-tow-006",
      "standard-pe-tow-007"
    ],
    "referenceStandardId": "standard-ohaus-5660-1",
    "measurementCategory": "MASA",
    "measurementType": "PESO",
    "model": "700E",
    "serialNumber": "",
    "measurementRange": "0.00 Kg - 5 Ton",
    "resolution": "0.1 Kg",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 15
  },
  {
    "id": "equipment-tow-ba-010",
    "code": "TOW-BA-010",
    "name": "BÁSCULA ELECTRÓNICA",
    "location": "TINTORERÍA",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-05-23",
    "nextDueDate": "2025-07-22",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de masa.",
    "referenceStandardIds": [
      "standard-ohaus-5660-1",
      "standard-pe-tow-001",
      "standard-pe-tow-002",
      "standard-pe-tow-003",
      "standard-pe-tow-004",
      "standard-pe-tow-005",
      "standard-pe-tow-006",
      "standard-pe-tow-007"
    ],
    "referenceStandardId": "standard-ohaus-5660-1",
    "measurementCategory": "MASA",
    "measurementType": "PESO",
    "model": "DIBATEC LUMINA",
    "serialNumber": "",
    "measurementRange": "0.00 Kg - 10 Kg",
    "resolution": "0.01 Kg",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 16
  },
  {
    "id": "equipment-tow-ba-011",
    "code": "TOW-BA-011",
    "name": "BÁSCULA ELECTRÓNICA",
    "location": "TINTORERÍA",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-05-23",
    "nextDueDate": "2025-07-22",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de masa.",
    "referenceStandardIds": [
      "standard-ohaus-5660-1",
      "standard-pe-tow-001",
      "standard-pe-tow-002",
      "standard-pe-tow-003",
      "standard-pe-tow-004",
      "standard-pe-tow-005",
      "standard-pe-tow-006",
      "standard-pe-tow-007"
    ],
    "referenceStandardId": "standard-ohaus-5660-1",
    "measurementCategory": "MASA",
    "measurementType": "PESO",
    "model": "DIBATEC MINI",
    "serialNumber": "MIN-2013-1319",
    "measurementRange": "0.000 Kg - 3 Kg",
    "resolution": "0.001 Kg",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 17
  },
  {
    "id": "equipment-tow-ba-012",
    "code": "TOW-BA-012",
    "name": "BÁSCULA ELECTRÓNICA",
    "location": "TINTORERÍA",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-05-23",
    "nextDueDate": "2025-07-22",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de masa.",
    "referenceStandardIds": [
      "standard-ohaus-5660-1",
      "standard-pe-tow-001",
      "standard-pe-tow-002",
      "standard-pe-tow-003",
      "standard-pe-tow-004",
      "standard-pe-tow-005",
      "standard-pe-tow-006",
      "standard-pe-tow-007"
    ],
    "referenceStandardId": "standard-ohaus-5660-1",
    "measurementCategory": "MASA",
    "measurementType": "PESO",
    "model": "DIBATEC PLATINO",
    "serialNumber": "-",
    "measurementRange": "0.20 kg - 10 Kg",
    "resolution": "0.01 Kg",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 18
  },
  {
    "id": "equipment-tow-ba-013",
    "code": "TOW-BA-013",
    "name": "BÁSCULA ELECTRÓNICA",
    "location": "TINTORERÍA",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-05-23",
    "nextDueDate": "2025-07-22",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de masa.",
    "referenceStandardIds": [
      "standard-ohaus-5660-1",
      "standard-pe-tow-001",
      "standard-pe-tow-002",
      "standard-pe-tow-003",
      "standard-pe-tow-004",
      "standard-pe-tow-005",
      "standard-pe-tow-006",
      "standard-pe-tow-007"
    ],
    "referenceStandardId": "standard-ohaus-5660-1",
    "measurementCategory": "MASA",
    "measurementType": "PESO",
    "model": "DIBATEC PLATINO",
    "serialNumber": "2017030759",
    "measurementRange": "0.0kg- 100kg",
    "resolution": "0.1Kg",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 19
  },
  {
    "id": "equipment-tow-ba-014",
    "code": "TOW-BA-014",
    "name": "PATIN BÁSCULA",
    "location": "SECADORA",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-06-10",
    "nextDueDate": "2025-08-09",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de masa.",
    "referenceStandardIds": [
      "standard-ohaus-5660-1",
      "standard-pe-tow-001",
      "standard-pe-tow-002",
      "standard-pe-tow-003",
      "standard-pe-tow-004",
      "standard-pe-tow-005",
      "standard-pe-tow-006",
      "standard-pe-tow-007"
    ],
    "referenceStandardId": "standard-ohaus-5660-1",
    "measurementCategory": "MASA",
    "measurementType": "PESO",
    "model": "NA",
    "serialNumber": "-",
    "measurementRange": "000.0 Kg - 2 Ton",
    "resolution": "000.1 Kg",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 20
  },
  {
    "id": "equipment-tow-ba-015",
    "code": "TOW-BA-015",
    "name": "BÁSCULA ELECTRÓNICA",
    "location": "COSTURA",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-06-11",
    "nextDueDate": "2025-08-10",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de masa.",
    "referenceStandardIds": [
      "standard-ohaus-5660-1",
      "standard-pe-tow-001",
      "standard-pe-tow-002",
      "standard-pe-tow-003",
      "standard-pe-tow-004",
      "standard-pe-tow-005",
      "standard-pe-tow-006",
      "standard-pe-tow-007"
    ],
    "referenceStandardId": "standard-ohaus-5660-1",
    "measurementCategory": "MASA",
    "measurementType": "PESO",
    "model": "Rhino BAPCA-500",
    "serialNumber": "-",
    "measurementRange": "000.00 Kg -500.00 Kg",
    "resolution": "0.50 Kg",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 21
  },
  {
    "id": "equipment-tow-ba-016",
    "code": "TOW-BA-016",
    "name": "BÁSCULA ELECTRÓNICA",
    "location": "COSTURA",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-05-22",
    "nextDueDate": "2025-07-21",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de masa.",
    "referenceStandardIds": [
      "standard-ohaus-5660-1",
      "standard-pe-tow-001",
      "standard-pe-tow-002",
      "standard-pe-tow-003",
      "standard-pe-tow-004",
      "standard-pe-tow-005",
      "standard-pe-tow-006",
      "standard-pe-tow-007"
    ],
    "referenceStandardId": "standard-ohaus-5660-1",
    "measurementCategory": "MASA",
    "measurementType": "PESO",
    "model": "Rhino BAPCA-500",
    "serialNumber": "HAPCA500-8337-31",
    "measurementRange": "000.00 Kg -500.00 Kg",
    "resolution": "0.50 Kg",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 22
  },
  {
    "id": "equipment-tow-ba-017",
    "code": "TOW-BA-017",
    "name": "BÁSCULA ELECTRÓNICA",
    "location": "COSTURA",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-05-23",
    "nextDueDate": "2025-07-22",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de masa.",
    "referenceStandardIds": [
      "standard-ohaus-5660-1",
      "standard-pe-tow-001",
      "standard-pe-tow-002",
      "standard-pe-tow-003",
      "standard-pe-tow-004",
      "standard-pe-tow-005",
      "standard-pe-tow-006",
      "standard-pe-tow-007"
    ],
    "referenceStandardId": "standard-ohaus-5660-1",
    "measurementCategory": "MASA",
    "measurementType": "PESO",
    "model": "DIABATEC MINI",
    "serialNumber": "-",
    "measurementRange": "0.00 Kg - 5.00 Kg",
    "resolution": "0.01 Kg",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 23
  },
  {
    "id": "equipment-tow-ba-018",
    "code": "TOW-BA-018",
    "name": "BÁSCULA ELECTRÓNICA",
    "location": "TINTORERÍA",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-06-11",
    "nextDueDate": "2025-08-10",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de masa.",
    "referenceStandardIds": [
      "standard-ohaus-5660-1",
      "standard-pe-tow-001",
      "standard-pe-tow-002",
      "standard-pe-tow-003",
      "standard-pe-tow-004",
      "standard-pe-tow-005",
      "standard-pe-tow-006",
      "standard-pe-tow-007"
    ],
    "referenceStandardId": "standard-ohaus-5660-1",
    "measurementCategory": "MASA",
    "measurementType": "PESO",
    "model": "DIABATEC MINI",
    "serialNumber": "M1200794",
    "measurementRange": "000.00 Kg -500.00 Kg",
    "resolution": "0.1 Kg",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 24
  },
  {
    "id": "equipment-tow-ba-019",
    "code": "TOW-BA-019",
    "name": "BÁSCULA ELECTRÓNICA",
    "location": "PT",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-06-11",
    "nextDueDate": "2025-08-10",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de masa.",
    "referenceStandardIds": [
      "standard-ohaus-5660-1",
      "standard-pe-tow-001",
      "standard-pe-tow-002",
      "standard-pe-tow-003",
      "standard-pe-tow-004",
      "standard-pe-tow-005",
      "standard-pe-tow-006",
      "standard-pe-tow-007"
    ],
    "referenceStandardId": "standard-ohaus-5660-1",
    "measurementCategory": "MASA",
    "measurementType": "PESO",
    "model": "Rhino I-PES",
    "serialNumber": "IPES-00037-0024",
    "measurementRange": "000.00 Kg - 50.00 Kg",
    "resolution": "0.1 Kg",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 25
  },
  {
    "id": "equipment-tow-ba-028",
    "code": "TOW-BA-028",
    "name": "BÁSCULA ELECTRÓNICA",
    "location": "CONFECCION DE BATA",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-05-23",
    "nextDueDate": "2025-07-22",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de masa.",
    "referenceStandardIds": [
      "standard-ohaus-5660-1",
      "standard-pe-tow-001",
      "standard-pe-tow-002",
      "standard-pe-tow-003",
      "standard-pe-tow-004",
      "standard-pe-tow-005",
      "standard-pe-tow-006",
      "standard-pe-tow-007"
    ],
    "referenceStandardId": "standard-ohaus-5660-1",
    "measurementCategory": "MASA",
    "measurementType": "PESO",
    "model": "Rhino I-PES",
    "serialNumber": "-",
    "measurementRange": "000.00 Kg - 500.00 Kg",
    "resolution": "0.1 Kg",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 26
  },
  {
    "id": "equipment-tow-ba-021",
    "code": "TOW-BA-021",
    "name": "BÁSCULA ELECTRÓNICA",
    "location": "PT",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-05-27",
    "nextDueDate": "2025-07-26",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de masa.",
    "referenceStandardIds": [
      "standard-ohaus-5660-1",
      "standard-pe-tow-001",
      "standard-pe-tow-002",
      "standard-pe-tow-003",
      "standard-pe-tow-004",
      "standard-pe-tow-005",
      "standard-pe-tow-006",
      "standard-pe-tow-007"
    ],
    "referenceStandardId": "standard-ohaus-5660-1",
    "measurementCategory": "MASA",
    "measurementType": "PESO",
    "model": "DIABATEC MINI",
    "serialNumber": "2022110025",
    "measurementRange": "000.00 Kg - 500.00 Kg",
    "resolution": "0.1 Kg",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 27
  },
  {
    "id": "equipment-tow-ba-022",
    "code": "TOW-BA-022",
    "name": "BÁSCULA ELECTRÓNICA",
    "location": "CORTE DE BATA",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-05-27",
    "nextDueDate": "2025-07-26",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de masa.",
    "referenceStandardIds": [
      "standard-ohaus-5660-1",
      "standard-pe-tow-001",
      "standard-pe-tow-002",
      "standard-pe-tow-003",
      "standard-pe-tow-004",
      "standard-pe-tow-005",
      "standard-pe-tow-006",
      "standard-pe-tow-007"
    ],
    "referenceStandardId": "standard-ohaus-5660-1",
    "measurementCategory": "MASA",
    "measurementType": "PESO",
    "model": "700E",
    "serialNumber": "6462250",
    "measurementRange": "000.00 Kg - 500.00 Kg",
    "resolution": "0.01kg",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 28
  },
  {
    "id": "equipment-tow-ba-023",
    "code": "TOW-BA-023",
    "name": "BÁSCULA ELECTRÓNICA",
    "location": "ENGOMADO wp3",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-04-09",
    "nextDueDate": "2025-06-08",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de masa.",
    "referenceStandardIds": [
      "standard-ohaus-5660-1",
      "standard-pe-tow-001",
      "standard-pe-tow-002",
      "standard-pe-tow-003",
      "standard-pe-tow-004",
      "standard-pe-tow-005",
      "standard-pe-tow-006",
      "standard-pe-tow-007"
    ],
    "referenceStandardId": "standard-ohaus-5660-1",
    "measurementCategory": "MASA",
    "measurementType": "PESO",
    "model": "OHAUS I-10",
    "serialNumber": "SN",
    "measurementRange": "000.0 Kg - 2 Ton",
    "resolution": "000.1 Kg",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 29
  },
  {
    "id": "equipment-tow-ba-024",
    "code": "TOW-BA-024",
    "name": "BÁSCULA ELECTRÓNICA",
    "location": "ENGOMADO wp3",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-05-27",
    "nextDueDate": "2025-07-26",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de masa.",
    "referenceStandardIds": [
      "standard-ohaus-5660-1",
      "standard-pe-tow-001",
      "standard-pe-tow-002",
      "standard-pe-tow-003",
      "standard-pe-tow-004",
      "standard-pe-tow-005",
      "standard-pe-tow-006",
      "standard-pe-tow-007"
    ],
    "referenceStandardId": "standard-ohaus-5660-1",
    "measurementCategory": "MASA",
    "measurementType": "PESO",
    "model": "TRANSCELL",
    "serialNumber": "SN",
    "measurementRange": "000.00 Kg - 50.00 Kg",
    "resolution": "0.01 Kg",
    "observations": "SE MANDA A MANTENIMIENTO",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 30
  },
  {
    "id": "equipment-tow-ba-025",
    "code": "TOW-BA-025",
    "name": "BÁSCULA ELECTRÓNICA",
    "location": "PT",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-06-11",
    "nextDueDate": "2025-08-10",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de masa.",
    "referenceStandardIds": [
      "standard-ohaus-5660-1",
      "standard-pe-tow-001",
      "standard-pe-tow-002",
      "standard-pe-tow-003",
      "standard-pe-tow-004",
      "standard-pe-tow-005",
      "standard-pe-tow-006",
      "standard-pe-tow-007"
    ],
    "referenceStandardId": "standard-ohaus-5660-1",
    "measurementCategory": "MASA",
    "measurementType": "PESO",
    "model": "TECNO COR-30",
    "serialNumber": "C103196",
    "measurementRange": "0.0000 g - 5.0000 g",
    "resolution": "0.0001 g",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 31
  },
  {
    "id": "equipment-tow-ba-026",
    "code": "TOW-BA-026",
    "name": "BÁSCULA ELECTRÓNICA",
    "location": "CORTE DE FELPA",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-05-27",
    "nextDueDate": "2025-07-26",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de masa.",
    "referenceStandardIds": [
      "standard-ohaus-5660-1",
      "standard-pe-tow-001",
      "standard-pe-tow-002",
      "standard-pe-tow-003",
      "standard-pe-tow-004",
      "standard-pe-tow-005",
      "standard-pe-tow-006",
      "standard-pe-tow-007"
    ],
    "referenceStandardId": "standard-ohaus-5660-1",
    "measurementCategory": "MASA",
    "measurementType": "PESO",
    "model": "Rhino I-QY",
    "serialNumber": "IQY-00131-0154",
    "measurementRange": "000.0 Kg - 2 Ton",
    "resolution": "000.1 Kg",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 32
  },
  {
    "id": "equipment-tow-ba-027",
    "code": "TOW-BA-027",
    "name": "BÁSCULA ELECTRÓNICA",
    "location": "COSTURA",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-04-09",
    "nextDueDate": "2025-06-08",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de masa.",
    "referenceStandardIds": [
      "standard-ohaus-5660-1",
      "standard-pe-tow-001",
      "standard-pe-tow-002",
      "standard-pe-tow-003",
      "standard-pe-tow-004",
      "standard-pe-tow-005",
      "standard-pe-tow-006",
      "standard-pe-tow-007"
    ],
    "referenceStandardId": "standard-ohaus-5660-1",
    "measurementCategory": "MASA",
    "measurementType": "PESO",
    "model": "Rhino BAPCA-500",
    "serialNumber": "-",
    "measurementRange": "000.00 Kg -500.00 Kg",
    "resolution": "0.50 Kg",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 33
  },
  {
    "id": "equipment-tow-lab-001",
    "code": "TOW-LAB-001",
    "name": "EQUIPO DE TINTURA",
    "location": "LABORATORÍO",
    "owner": "Calidad",
    "activity": "calibration",
    "frequencyMonths": 12,
    "frequencyDays": 360,
    "lastCompletedAt": "2025-02-26",
    "nextDueDate": "2026-02-21",
    "evidenceCount": 0,
    "standard": "Calibración externa conforme al programa F-CA-37.",
    "externalProvider": "Proveedor pendiente de asignar",
    "measurementCategory": "LABORATORÍO",
    "measurementType": "CELSIUS",
    "model": "RADIANT",
    "serialNumber": "SN",
    "measurementRange": "T. ambiente °C - 140 °C",
    "resolution": "1 °C",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 49
  },
  {
    "id": "equipment-tow-lab-002",
    "code": "TOW-LAB-002",
    "name": "BALANZA ELECTRÓNICA",
    "location": "LABORATORÍO",
    "owner": "Calidad",
    "activity": "calibration",
    "frequencyMonths": 12,
    "frequencyDays": 360,
    "lastCompletedAt": "2025-02-26",
    "nextDueDate": "2026-02-21",
    "evidenceCount": 0,
    "standard": "Calibración externa conforme al programa F-CA-37.",
    "externalProvider": "Proveedor pendiente de asignar",
    "measurementCategory": "LABORATORÍO",
    "measurementType": "MASA",
    "model": "Heng2Heng",
    "serialNumber": "SN",
    "measurementRange": "0.0001 g - 200.0000 g",
    "resolution": "0.0001 g",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 50
  },
  {
    "id": "equipment-tow-lab-003",
    "code": "TOW-LAB-003",
    "name": "LUMITESTER",
    "location": "LABORATORÍO",
    "owner": "Calidad",
    "activity": "calibration",
    "frequencyMonths": 12,
    "frequencyDays": 360,
    "lastCompletedAt": "2024-05-07",
    "nextDueDate": "2025-05-02",
    "evidenceCount": 0,
    "standard": "Calibración externa conforme al programa F-CA-37.",
    "externalProvider": "Proveedor pendiente de asignar",
    "measurementCategory": "LABORATORÍO",
    "measurementType": "LUXES",
    "model": "SUTTEX",
    "serialNumber": "SN",
    "measurementRange": "2000 lx 0 - 4150 K",
    "resolution": "1 lx 1 K",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 51
  },
  {
    "id": "equipment-tow-lab-004",
    "code": "TOW-LAB-004",
    "name": "PRECISION COLORIMETER",
    "location": "LABORATORÍO",
    "owner": "Calidad",
    "activity": "calibration",
    "frequencyMonths": 12,
    "frequencyDays": 360,
    "lastCompletedAt": "",
    "nextDueDate": "",
    "evidenceCount": 0,
    "standard": "Calibración externa conforme al programa F-CA-37.",
    "externalProvider": "Proveedor pendiente de asignar",
    "measurementCategory": "LABORATORÍO",
    "measurementType": "COLOR",
    "model": "3nh",
    "serialNumber": "1501823",
    "measurementRange": "",
    "resolution": "",
    "observations": "",
    "schedulePending": true,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 52
  },
  {
    "id": "equipment-tow-lab-005",
    "code": "TOW-LAB-005",
    "name": "REFRACTÓMETRO BRIX",
    "location": "LABORATORÍO",
    "owner": "Calidad",
    "activity": "calibration",
    "frequencyMonths": 12,
    "frequencyDays": 360,
    "lastCompletedAt": "2025-04-09",
    "nextDueDate": "2026-04-04",
    "evidenceCount": 0,
    "standard": "Calibración externa conforme al programa F-CA-37.",
    "externalProvider": "Proveedor pendiente de asignar",
    "measurementCategory": "LABORATORÍO",
    "measurementType": "% SÓLIDOS",
    "model": "ATAGO",
    "serialNumber": "000379326-0001",
    "measurementRange": "0-30 BRIX",
    "resolution": "20°C",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 53
  },
  {
    "id": "equipment-tow-lab-006",
    "code": "TOW-LAB-006",
    "name": "REFRACTÓMETRO BRIX",
    "location": "ENGOMADO",
    "owner": "Calidad",
    "activity": "calibration",
    "frequencyMonths": 12,
    "frequencyDays": 360,
    "lastCompletedAt": "",
    "nextDueDate": "",
    "evidenceCount": 0,
    "standard": "Calibración externa conforme al programa F-CA-37.",
    "externalProvider": "Proveedor pendiente de asignar",
    "measurementCategory": "LABORATORÍO",
    "measurementType": "% SÓLIDOS",
    "model": "ATC",
    "serialNumber": "SN",
    "measurementRange": "0-10 BRIX",
    "resolution": "20°C",
    "observations": "",
    "schedulePending": true,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 54
  },
  {
    "id": "equipment-tow-lab-007",
    "code": "TOW-LAB-007",
    "name": "CABINA DE ILUMINACIÓN",
    "location": "CALIDAD",
    "owner": "Calidad",
    "activity": "calibration",
    "frequencyMonths": 12,
    "frequencyDays": 360,
    "lastCompletedAt": "2025-05-12",
    "nextDueDate": "2026-05-07",
    "evidenceCount": 0,
    "standard": "Calibración externa conforme al programa F-CA-37.",
    "externalProvider": "Proveedor pendiente de asignar",
    "measurementCategory": "LABORATORÍO",
    "measurementType": "COLOR",
    "model": "SUTTEX",
    "serialNumber": "SN",
    "measurementRange": "0",
    "resolution": "1 LX",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 55
  },
  {
    "id": "equipment-tow-lab-008",
    "code": "TOW-LAB-008",
    "name": "PH",
    "location": "LABORATORÍO",
    "owner": "Calidad",
    "activity": "calibration",
    "frequencyMonths": 12,
    "frequencyDays": 360,
    "lastCompletedAt": "2025-02-26",
    "nextDueDate": "2026-02-21",
    "evidenceCount": 0,
    "standard": "Calibración externa conforme al programa F-CA-37.",
    "externalProvider": "Proveedor pendiente de asignar",
    "measurementCategory": "LABORATORÍO",
    "measurementType": "CONDUCTIVIDAD , PH",
    "model": "PCE-PHD1",
    "serialNumber": "T.073644",
    "measurementRange": "PH 0.0 - PH 14",
    "resolution": "0.01 PH",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 56
  },
  {
    "id": "equipment-tow-lab-009",
    "code": "TOW-LAB-009",
    "name": "PH",
    "location": "LABORATORÍO",
    "owner": "Calidad",
    "activity": "calibration",
    "frequencyMonths": 12,
    "frequencyDays": 360,
    "lastCompletedAt": "",
    "nextDueDate": "",
    "evidenceCount": 0,
    "standard": "Calibración externa conforme al programa F-CA-37.",
    "externalProvider": "Proveedor pendiente de asignar",
    "measurementCategory": "LABORATORÍO",
    "measurementType": "PH",
    "model": "CONDUCTRONIC PH10",
    "serialNumber": "10784",
    "measurementRange": "PH-2 / PH-16",
    "resolution": "P14",
    "observations": "NO SIRVE EL ELECTRODO (SE BUSCA UNO NUEVO).",
    "schedulePending": true,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 57
  },
  {
    "id": "equipment-tow-lon-001",
    "code": "TOW-LON-001",
    "name": "FLEXÓMETRO ANÁLOGICO",
    "location": "CRUDO",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-05-28",
    "nextDueDate": "2025-07-27",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de longitud.",
    "referenceStandardIds": [
      "standard-tow-lon-01"
    ],
    "referenceStandardId": "standard-tow-lon-01",
    "measurementCategory": "LONGITUD",
    "measurementType": "LONGITUD",
    "model": "TRUPER FH-3M",
    "serialNumber": "SN",
    "measurementRange": "0.00 m - 3.00 m",
    "resolution": "0.01 m",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 63
  },
  {
    "id": "equipment-tow-lon-002",
    "code": "TOW-LON-002",
    "name": "FLEXÓMETRO ANÁLOGICO",
    "location": "CRUDO",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-03-27",
    "nextDueDate": "2025-05-26",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de longitud.",
    "referenceStandardIds": [
      "standard-tow-lon-01"
    ],
    "referenceStandardId": "standard-tow-lon-01",
    "measurementCategory": "LONGITUD",
    "measurementType": "LONGITUD",
    "model": "TRUPER FH-3M",
    "serialNumber": "SN",
    "measurementRange": "0.00 m - 3.00 m",
    "resolution": "0.01 m",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 64
  },
  {
    "id": "equipment-tow-lon-003",
    "code": "TOW-LON-003",
    "name": "FLEXÓMETRO ANÁLOGICO",
    "location": "COSTURA",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-03-31",
    "nextDueDate": "2025-05-30",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de longitud.",
    "referenceStandardIds": [
      "standard-tow-lon-01"
    ],
    "referenceStandardId": "standard-tow-lon-01",
    "measurementCategory": "LONGITUD",
    "measurementType": "LONGITUD",
    "model": "TRUPER FH-5M",
    "serialNumber": "SN",
    "measurementRange": "0.00 m - 5.00 m",
    "resolution": "0.01 m",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 65
  },
  {
    "id": "equipment-tow-lon-004",
    "code": "TOW-LON-004",
    "name": "FLEXÓMETRO ANÁLOGICO",
    "location": "COSTURA",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-06-02",
    "nextDueDate": "2025-08-01",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de longitud.",
    "referenceStandardIds": [
      "standard-tow-lon-01"
    ],
    "referenceStandardId": "standard-tow-lon-01",
    "measurementCategory": "LONGITUD",
    "measurementType": "LONGITUD",
    "model": "TRUPER FH-5M",
    "serialNumber": "SN",
    "measurementRange": "0.00 m - 5.00 m",
    "resolution": "0.01 m",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 66
  },
  {
    "id": "equipment-tow-lon-005",
    "code": "TOW-LON-005",
    "name": "FLEXÓMETRO ANÁLOGICO",
    "location": "COSTURA",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-06-02",
    "nextDueDate": "2025-08-01",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de longitud.",
    "referenceStandardIds": [
      "standard-tow-lon-01"
    ],
    "referenceStandardId": "standard-tow-lon-01",
    "measurementCategory": "LONGITUD",
    "measurementType": "LONGITUD",
    "model": "TRUPER FH-3M",
    "serialNumber": "SN",
    "measurementRange": "0.00 m - 3.00 m",
    "resolution": "0.01 m",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 67
  },
  {
    "id": "equipment-tow-lon-006",
    "code": "TOW-LON-006",
    "name": "FLEXÓMETRO ANÁLOGICO",
    "location": "COSTURA",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-06-02",
    "nextDueDate": "2025-08-01",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de longitud.",
    "referenceStandardIds": [
      "standard-tow-lon-01"
    ],
    "referenceStandardId": "standard-tow-lon-01",
    "measurementCategory": "LONGITUD",
    "measurementType": "LONGITUD",
    "model": "TRUPER GRIPPER",
    "serialNumber": "SN",
    "measurementRange": "0.00 m - 3.00 m",
    "resolution": "0.01 m",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 68
  },
  {
    "id": "equipment-tow-lon-007",
    "code": "TOW-LON-007",
    "name": "FLEXÓMETRO ANÁLOGICO",
    "location": "CRUDO",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-05-29",
    "nextDueDate": "2025-07-28",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de longitud.",
    "referenceStandardIds": [
      "standard-tow-lon-01"
    ],
    "referenceStandardId": "standard-tow-lon-01",
    "measurementCategory": "LONGITUD",
    "measurementType": "LONGITUD",
    "model": "TRUPER FH-5M",
    "serialNumber": "SN",
    "measurementRange": "0.00 m - 5.00 m",
    "resolution": "0.01 m",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 69
  },
  {
    "id": "equipment-tow-lon-008",
    "code": "TOW-LON-008",
    "name": "CINTA MÉTRICA",
    "location": "COSTURA",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-03-31",
    "nextDueDate": "2025-05-30",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de longitud.",
    "referenceStandardIds": [
      "standard-tow-lon-01"
    ],
    "referenceStandardId": "standard-tow-lon-01",
    "measurementCategory": "LONGITUD",
    "measurementType": "LONGITUD",
    "model": "HOECHST MASS",
    "serialNumber": "SN",
    "measurementRange": "0.0 cm - 305.0 cm",
    "resolution": "0.1 cm",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 70
  },
  {
    "id": "equipment-tow-lon-009",
    "code": "TOW-LON-009",
    "name": "FLEXÓMETRO ANÁLOGICO",
    "location": "ENGOMADO wp3",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-06-02",
    "nextDueDate": "2025-08-01",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de longitud.",
    "referenceStandardIds": [
      "standard-tow-lon-01"
    ],
    "referenceStandardId": "standard-tow-lon-01",
    "measurementCategory": "LONGITUD",
    "measurementType": "LONGITUD",
    "model": "URREA 5M",
    "serialNumber": "1595LSW",
    "measurementRange": "0.00 m - 5.00 m",
    "resolution": "0.01 m",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 71
  },
  {
    "id": "equipment-tow-lon-010",
    "code": "TOW-LON-010",
    "name": "FLEXÓMETRO ANÁLOGICO",
    "location": "ENGOMADO wp2",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-03-31",
    "nextDueDate": "2025-05-30",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de longitud.",
    "referenceStandardIds": [
      "standard-tow-lon-01"
    ],
    "referenceStandardId": "standard-tow-lon-01",
    "measurementCategory": "LONGITUD",
    "measurementType": "LONGITUD",
    "model": "BöRK 5M",
    "serialNumber": "SN",
    "measurementRange": "0.00 m - 5.00 m",
    "resolution": "0.01 m",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 72
  },
  {
    "id": "equipment-tow-lon-011",
    "code": "TOW-LON-011",
    "name": "FLEXÓMETRO ANÁLOGICO",
    "location": "TEJIDO",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "",
    "nextDueDate": "",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de longitud.",
    "referenceStandardIds": [
      "standard-tow-lon-01"
    ],
    "referenceStandardId": "standard-tow-lon-01",
    "measurementCategory": "LONGITUD",
    "measurementType": "LONGITUD",
    "model": "TRUPER FH-3M",
    "serialNumber": "SN",
    "measurementRange": "0.00 m - 3.00 m",
    "resolution": "0.01 m",
    "observations": "",
    "schedulePending": true,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 73
  },
  {
    "id": "equipment-tow-lon-012",
    "code": "TOW-LON-012",
    "name": "FLEXÓMETRO ANÁLOGICO",
    "location": "SECADORA",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-06-02",
    "nextDueDate": "2025-08-01",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de longitud.",
    "referenceStandardIds": [
      "standard-tow-lon-01"
    ],
    "referenceStandardId": "standard-tow-lon-01",
    "measurementCategory": "LONGITUD",
    "measurementType": "LONGITUD",
    "model": "TRUPER FH-5M",
    "serialNumber": "SN",
    "measurementRange": "0.00 m - 5.00 m",
    "resolution": "0.01 m",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 74
  },
  {
    "id": "equipment-tow-lon-013",
    "code": "TOW-LON-013",
    "name": "FLEXÓMETRO ANÁLOGICO",
    "location": "CALIDAD",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "",
    "nextDueDate": "",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de longitud.",
    "referenceStandardIds": [
      "standard-tow-lon-01"
    ],
    "referenceStandardId": "standard-tow-lon-01",
    "measurementCategory": "LONGITUD",
    "measurementType": "LONGITUD",
    "model": "TRUPER FH-3M",
    "serialNumber": "SN",
    "measurementRange": "0.00 m - 3.00 m",
    "resolution": "0.01 m",
    "observations": "PENDIENTE",
    "schedulePending": true,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 75
  },
  {
    "id": "equipment-tow-lon-014",
    "code": "TOW-LON-014",
    "name": "FLEXÓMETRO ANÁLOGICO",
    "location": "CALIDAD",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-05-29",
    "nextDueDate": "2025-07-28",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de longitud.",
    "referenceStandardIds": [
      "standard-tow-lon-01"
    ],
    "referenceStandardId": "standard-tow-lon-01",
    "measurementCategory": "LONGITUD",
    "measurementType": "LONGITUD",
    "model": "TRUPER FH-3M",
    "serialNumber": "SN",
    "measurementRange": "0.00 m - 3.00 m",
    "resolution": "0.01 m",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 76
  },
  {
    "id": "equipment-tow-lon-015",
    "code": "TOW-LON-015",
    "name": "FLEXÓMETRO ANÁLOGICO",
    "location": "CALIDAD",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-05-29",
    "nextDueDate": "2025-07-28",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de longitud.",
    "referenceStandardIds": [
      "standard-tow-lon-01"
    ],
    "referenceStandardId": "standard-tow-lon-01",
    "measurementCategory": "LONGITUD",
    "measurementType": "LONGITUD",
    "model": "URREA 5M",
    "serialNumber": "1595LSW",
    "measurementRange": "0.00 m - 5.00 m",
    "resolution": "0.01 m",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 77
  },
  {
    "id": "equipment-tow-lon-016",
    "code": "TOW-LON-016",
    "name": "CINTA MÉTRICA",
    "location": "CALIDAD",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-05-29",
    "nextDueDate": "2025-07-28",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de longitud.",
    "referenceStandardIds": [
      "standard-tow-lon-01"
    ],
    "referenceStandardId": "standard-tow-lon-01",
    "measurementCategory": "LONGITUD",
    "measurementType": "LONGITUD",
    "model": "HOECHST MASS",
    "serialNumber": "SN",
    "measurementRange": "0.0 cm - 305.0 cm",
    "resolution": "0.1 cm",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 78
  },
  {
    "id": "equipment-tow-lon-017",
    "code": "TOW-LON-017",
    "name": "FLEXÓMETRO ANÁLOGICO",
    "location": "PT",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-06-02",
    "nextDueDate": "2025-08-01",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de longitud.",
    "referenceStandardIds": [
      "standard-tow-lon-01"
    ],
    "referenceStandardId": "standard-tow-lon-01",
    "measurementCategory": "LONGITUD",
    "measurementType": "LONGITUD",
    "model": "URREA 5M",
    "serialNumber": "1595LSW",
    "measurementRange": "0.00 m - 5.00 m",
    "resolution": "0.01 m",
    "observations": "Tomar solo de referencia",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 79
  },
  {
    "id": "equipment-tow-lon-018",
    "code": "TOW-LON-018",
    "name": "FLEXÓMETRO ANÁLOGICO",
    "location": "PT",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-06-02",
    "nextDueDate": "2025-08-01",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de longitud.",
    "referenceStandardIds": [
      "standard-tow-lon-01"
    ],
    "referenceStandardId": "standard-tow-lon-01",
    "measurementCategory": "LONGITUD",
    "measurementType": "LONGITUD",
    "model": "TRUPER FH-5M",
    "serialNumber": "SN",
    "measurementRange": "0.00 m - 5.00 m",
    "resolution": "0.01 m",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 80
  },
  {
    "id": "equipment-tow-lon-019",
    "code": "TOW-LON-019",
    "name": "FLEXÓMETRO ANÁLOGICO",
    "location": "PT",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-06-02",
    "nextDueDate": "2025-08-01",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de longitud.",
    "referenceStandardIds": [
      "standard-tow-lon-01"
    ],
    "referenceStandardId": "standard-tow-lon-01",
    "measurementCategory": "LONGITUD",
    "measurementType": "LONGITUD",
    "model": "TRUPER FH-3M",
    "serialNumber": "SN",
    "measurementRange": "0.00 m - 3.00 m",
    "resolution": "0.01 m",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 81
  },
  {
    "id": "equipment-tow-lon-020",
    "code": "TOW-LON-020",
    "name": "CINTA MÉTRICA",
    "location": "CALIDAD",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-05-29",
    "nextDueDate": "2025-07-28",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de longitud.",
    "referenceStandardIds": [
      "standard-tow-lon-01"
    ],
    "referenceStandardId": "standard-tow-lon-01",
    "measurementCategory": "LONGITUD",
    "measurementType": "LONGITUD",
    "model": "HOECHST MASS",
    "serialNumber": "SN",
    "measurementRange": "0.0 cm - 305.0 cm",
    "resolution": "0.1 cm",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 82
  },
  {
    "id": "equipment-tow-lon-021",
    "code": "TOW-LON-021",
    "name": "FLEXÓMETRO ANÁLOGICO",
    "location": "PT/CALIDAD",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-03-31",
    "nextDueDate": "2025-05-30",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de longitud.",
    "referenceStandardIds": [
      "standard-tow-lon-01"
    ],
    "referenceStandardId": "standard-tow-lon-01",
    "measurementCategory": "LONGITUD",
    "measurementType": "LONGITUD",
    "model": "URREA 5M",
    "serialNumber": "SN",
    "measurementRange": "0.00 m - 5.00 m",
    "resolution": "0.01 m",
    "observations": "Tomar solo de referencia, punta doblada y escala desgastada.",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 83
  },
  {
    "id": "equipment-tow-lon-022",
    "code": "TOW-LON-022",
    "name": "FLEXÓMETRO ANÁLOGICO",
    "location": "pendiente",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-03-31",
    "nextDueDate": "2025-05-30",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de longitud.",
    "referenceStandardIds": [
      "standard-tow-lon-01"
    ],
    "referenceStandardId": "standard-tow-lon-01",
    "measurementCategory": "LONGITUD",
    "measurementType": "LONGITUD",
    "model": "TRUPER GRIPPER",
    "serialNumber": "SN",
    "measurementRange": "0.00 m - 3.00 m",
    "resolution": "0.01 m",
    "observations": "Tomar solo de referencia, punta doblada y escala desgastada.",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 84
  },
  {
    "id": "equipment-tow-lon-023",
    "code": "TOW-LON-023",
    "name": "CINTA MÉTRICA",
    "location": "CALIDAD",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-05-30",
    "nextDueDate": "2025-07-29",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de longitud.",
    "referenceStandardIds": [
      "standard-tow-lon-01"
    ],
    "referenceStandardId": "standard-tow-lon-01",
    "measurementCategory": "LONGITUD",
    "measurementType": "LONGITUD",
    "model": "HOECHST MASS",
    "serialNumber": "SN",
    "measurementRange": "0.0 cm - 30.0 cm",
    "resolution": "0.1 cm",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 85
  },
  {
    "id": "equipment-tow-lon-024",
    "code": "TOW-LON-024",
    "name": "CINTA MÉTRICA GRANDE",
    "location": "MANTENIMIENTO",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-04-30",
    "nextDueDate": "2025-06-29",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de longitud.",
    "referenceStandardIds": [
      "standard-tow-lon-01"
    ],
    "referenceStandardId": "standard-tow-lon-01",
    "measurementCategory": "LONGITUD",
    "measurementType": "LONGITUD",
    "model": "TRUPER 12M",
    "serialNumber": "SN",
    "measurementRange": "0.0m- 12m",
    "resolution": "0.01 m",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 86
  },
  {
    "id": "equipment-tow-lon-025",
    "code": "TOW-LON-025",
    "name": "FLEXÓMETRO ANÁLOGICO",
    "location": "LABORATORIO",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-04-30",
    "nextDueDate": "2025-06-29",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de longitud.",
    "referenceStandardIds": [
      "standard-tow-lon-01"
    ],
    "referenceStandardId": "standard-tow-lon-01",
    "measurementCategory": "LONGITUD",
    "measurementType": "LONGITUD",
    "model": "SURTEX",
    "serialNumber": "B122081",
    "measurementRange": "0.0m - 5m",
    "resolution": "0.01m",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 87
  },
  {
    "id": "equipment-tow-lon-026",
    "code": "TOW-LON-026",
    "name": "FLEXÓMETRO ANÁLOGICO",
    "location": "LABORATORIO",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-04-30",
    "nextDueDate": "2025-06-29",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de longitud.",
    "referenceStandardIds": [
      "standard-tow-lon-01"
    ],
    "referenceStandardId": "standard-tow-lon-01",
    "measurementCategory": "LONGITUD",
    "measurementType": "LONGITUD",
    "model": "TRUPER GRIPPER",
    "serialNumber": "SN",
    "measurementRange": "0.0m -3.0 m",
    "resolution": "0.01m",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 88
  },
  {
    "id": "equipment-tow-lon-027",
    "code": "TOW-LON-027",
    "name": "CINTA METRICA",
    "location": "CONFECCION BATA",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-05-13",
    "nextDueDate": "2025-07-12",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de longitud.",
    "referenceStandardIds": [
      "standard-tow-lon-01"
    ],
    "referenceStandardId": "standard-tow-lon-01",
    "measurementCategory": "LONGITUD",
    "measurementType": "LONGITUD",
    "model": "SN",
    "serialNumber": "SN",
    "measurementRange": "0.0cm - 150 cm",
    "resolution": "0.1cm",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 89
  },
  {
    "id": "equipment-tow-lon-028",
    "code": "TOW-LON-028",
    "name": "CINTA METRICA",
    "location": "CONFECCION BATA",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-05-13",
    "nextDueDate": "2025-07-12",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de longitud.",
    "referenceStandardIds": [
      "standard-tow-lon-01"
    ],
    "referenceStandardId": "standard-tow-lon-01",
    "measurementCategory": "LONGITUD",
    "measurementType": "LONGITUD",
    "model": "SN",
    "serialNumber": "SN",
    "measurementRange": "0.0cm - 150 cm",
    "resolution": "0.1 cm",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 90
  },
  {
    "id": "equipment-tow-lon-029",
    "code": "TOW-LON-029",
    "name": "FLEXÓMETRO ANÁLOGICO",
    "location": "CONFECCION BATA",
    "owner": "Calidad",
    "activity": "verification",
    "frequencyMonths": 2,
    "frequencyDays": 60,
    "lastCompletedAt": "2025-05-20",
    "nextDueDate": "2025-07-19",
    "evidenceCount": 0,
    "standard": "Verificación interna conforme al F-CA-37 con patrones calibrados de longitud.",
    "referenceStandardIds": [
      "standard-tow-lon-01"
    ],
    "referenceStandardId": "standard-tow-lon-01",
    "measurementCategory": "LONGITUD",
    "measurementType": "LONGITUD",
    "model": "TOOCFRAFT 3M",
    "serialNumber": "TC0236",
    "measurementRange": "0.00 - 3.0m",
    "resolution": "0.01 m",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 91
  },
  {
    "id": "equipment-tow-tem-001",
    "code": "TOW-TEM-001",
    "name": "TERMOHIGROMETRO",
    "location": "TEJIDO",
    "owner": "Calidad",
    "activity": "calibration",
    "frequencyMonths": 12,
    "frequencyDays": 360,
    "lastCompletedAt": "2024-06-19",
    "nextDueDate": "2025-06-14",
    "evidenceCount": 0,
    "standard": "Calibración externa conforme al programa F-CA-37.",
    "externalProvider": "Proveedor pendiente de asignar",
    "measurementCategory": "TEMPERATURA/HUMEDAD",
    "measurementType": "HUMEDAD/TEMP",
    "model": "UPLAYTECK",
    "serialNumber": "B0B1V1G7SG",
    "measurementRange": "TEMPERATURA: -20°C/50°C HUMEDAD: 10%-99%",
    "resolution": "TEMPERATURA : ±0.1°C HUMEDAD: ±10%",
    "observations": "no habra para esta fecxha",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 96
  },
  {
    "id": "equipment-tow-tem-002",
    "code": "TOW-TEM-002",
    "name": "TERMOHIGROMETRO",
    "location": "TEJIDO",
    "owner": "Calidad",
    "activity": "calibration",
    "frequencyMonths": 12,
    "frequencyDays": 360,
    "lastCompletedAt": "2024-06-19",
    "nextDueDate": "2025-06-14",
    "evidenceCount": 0,
    "standard": "Calibración externa conforme al programa F-CA-37.",
    "externalProvider": "Proveedor pendiente de asignar",
    "measurementCategory": "TEMPERATURA/HUMEDAD",
    "measurementType": "HUMEDAD/TEMP",
    "model": "TAYLOR 1732",
    "serialNumber": "NA",
    "measurementRange": "TEMPERATURA: -10°C/50°C HUMEDAD: 20%-95%",
    "resolution": "TEMPERATURA : ±0.5°C HUMEDAD: ±3%",
    "observations": "no habra para esta fecxha",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 97
  },
  {
    "id": "equipment-tow-tem-003",
    "code": "TOW-TEM-003",
    "name": "TERMOHIGROMETRO",
    "location": "TEJIDO",
    "owner": "Calidad",
    "activity": "calibration",
    "frequencyMonths": 12,
    "frequencyDays": 360,
    "lastCompletedAt": "2024-06-19",
    "nextDueDate": "2025-06-14",
    "evidenceCount": 0,
    "standard": "Calibración externa conforme al programa F-CA-37.",
    "externalProvider": "Proveedor pendiente de asignar",
    "measurementCategory": "TEMPERATURA/HUMEDAD",
    "measurementType": "HUMEDAD/TEMP",
    "model": "pendiente",
    "serialNumber": "NA",
    "measurementRange": "TEMPERATURA: -20°C/50°C HUMEDAD: 10%-99%",
    "resolution": "TEMPERATURA : ±0.5°C HUMEDAD: ±3%",
    "observations": "no habra para esta fecxha",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 98
  },
  {
    "id": "equipment-tow-tem-004",
    "code": "TOW-TEM-004",
    "name": "TERMOHIGROMETRO",
    "location": "TEJIDO",
    "owner": "Calidad",
    "activity": "calibration",
    "frequencyMonths": 12,
    "frequencyDays": 360,
    "lastCompletedAt": "2024-06-19",
    "nextDueDate": "2025-06-14",
    "evidenceCount": 0,
    "standard": "Calibración externa conforme al programa F-CA-37.",
    "externalProvider": "Proveedor pendiente de asignar",
    "measurementCategory": "TEMPERATURA/HUMEDAD",
    "measurementType": "HUMEDAD/TEMP",
    "model": "TAYLOR 1732",
    "serialNumber": "NA",
    "measurementRange": "TEMPERATURA: -10°C/50°C HUMEDAD: 20%-95%",
    "resolution": "TEMPERATURA : ±0.5°C HUMEDAD: ±3%",
    "observations": "YA NO SRIVE DISPLAY",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 99
  },
  {
    "id": "equipment-tow-tem-005",
    "code": "TOW-TEM-005",
    "name": "INDICADOR DE TEMPERATURA",
    "location": "CALIDAD",
    "owner": "Calidad",
    "activity": "calibration",
    "frequencyMonths": 12,
    "frequencyDays": 360,
    "lastCompletedAt": "2025-02-17",
    "nextDueDate": "2026-02-12",
    "evidenceCount": 0,
    "standard": "Calibración externa conforme al programa F-CA-37.",
    "externalProvider": "Proveedor pendiente de asignar",
    "measurementCategory": "TEMPERATURA/HUMEDAD",
    "measurementType": "CELSIUS",
    "model": "TM-902 C",
    "serialNumber": "SN",
    "measurementRange": "-50 /1300°C",
    "resolution": "0.1°C",
    "observations": "",
    "schedulePending": false,
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 100
  },
  {
    "id": "standard-ohaus-5660-1",
    "code": "S/N",
    "name": "Set de pesas Modelo: Sin modelo Instrument",
    "location": "Calidad",
    "owner": "Calidad",
    "activity": "calibration",
    "frequencyMonths": 12,
    "lastCompletedAt": "2024-06-24",
    "nextDueDate": "2025-06-24",
    "evidenceCount": 1,
    "standard": "Informe de calibración MA22-5142",
    "isReferenceStandard": true,
    "externalProvider": "COMINTEC",
    "measurementType": "Pesos",
    "brand": "OHAUS",
    "serialNumber": "5660-1",
    "measurementRange": "1 g a 1000 g",
    "resolution": "NA",
    "calibrationReport": "MA22-5142",
    "observations": "En tiempo",
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 4
  },
  {
    "id": "standard-pe-tow-001",
    "code": "PE-TOW-001",
    "name": "Pesa paralelepipeda",
    "location": "Calidad",
    "owner": "Calidad",
    "activity": "calibration",
    "frequencyMonths": 12,
    "lastCompletedAt": "2024-10-29",
    "nextDueDate": "2025-10-29",
    "evidenceCount": 1,
    "standard": "Informe de calibración COM-24-IC-05188P",
    "isReferenceStandard": true,
    "externalProvider": "COMINTEC",
    "measurementType": "Pesos",
    "brand": "ACCURATE",
    "serialNumber": "151816174",
    "measurementRange": "20kg",
    "resolution": "NA",
    "calibrationReport": "COM-24-IC-05188P",
    "observations": "En tiempo",
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 5
  },
  {
    "id": "standard-pe-tow-002",
    "code": "PE-TOW-002",
    "name": "Pesa paralelepipeda",
    "location": "Calidad",
    "owner": "Calidad",
    "activity": "calibration",
    "frequencyMonths": 12,
    "lastCompletedAt": "2024-10-29",
    "nextDueDate": "2025-10-29",
    "evidenceCount": 1,
    "standard": "Informe de calibración MA22-5144",
    "isReferenceStandard": true,
    "externalProvider": "COMINTEC",
    "measurementType": "Pesos",
    "brand": "ACCURATE",
    "serialNumber": "15181673",
    "measurementRange": "20kg",
    "resolution": "NA",
    "calibrationReport": "MA22-5144",
    "observations": "En tiempo",
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 6
  },
  {
    "id": "standard-pe-tow-003",
    "code": "PE-TOW-003",
    "name": "Pesa paralelepipeda",
    "location": "Calidad",
    "owner": "Calidad",
    "activity": "calibration",
    "frequencyMonths": 12,
    "lastCompletedAt": "2024-10-29",
    "nextDueDate": "2025-10-29",
    "evidenceCount": 1,
    "standard": "Informe de calibración MA22-5144",
    "isReferenceStandard": true,
    "externalProvider": "COMINTEC",
    "measurementType": "Pesos",
    "brand": "ACCURATE",
    "serialNumber": "151816172",
    "measurementRange": "20kg",
    "resolution": "NA",
    "calibrationReport": "MA22-5144",
    "observations": "En tiempo",
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 7
  },
  {
    "id": "standard-pe-tow-004",
    "code": "PE-TOW-004",
    "name": "Pesa paralelepipeda",
    "location": "Calidad",
    "owner": "Calidad",
    "activity": "calibration",
    "frequencyMonths": 12,
    "lastCompletedAt": "2024-10-29",
    "nextDueDate": "2025-10-29",
    "evidenceCount": 1,
    "standard": "Informe de calibración MA22-5144",
    "isReferenceStandard": true,
    "externalProvider": "COMINTEC",
    "measurementType": "Pesos",
    "brand": "ACCURATE",
    "serialNumber": "151816171",
    "measurementRange": "20kg",
    "resolution": "NA",
    "calibrationReport": "MA22-5144",
    "observations": "En tiempo",
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 8
  },
  {
    "id": "standard-pe-tow-005",
    "code": "PE-TOW-005",
    "name": "Pesa paralelepipeda",
    "location": "Calidad",
    "owner": "Calidad",
    "activity": "calibration",
    "frequencyMonths": 12,
    "lastCompletedAt": "2024-10-29",
    "nextDueDate": "2025-10-29",
    "evidenceCount": 1,
    "standard": "Informe de calibración MA22-5144",
    "isReferenceStandard": true,
    "externalProvider": "COMINTEC",
    "measurementType": "Pesos",
    "brand": "ACCURATE",
    "serialNumber": "151816176",
    "measurementRange": "10kg",
    "resolution": "NA",
    "calibrationReport": "MA22-5144",
    "observations": "En tiempo",
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 9
  },
  {
    "id": "standard-pe-tow-006",
    "code": "PE-TOW-006",
    "name": "Pesa paralelepipeda",
    "location": "Calidad",
    "owner": "Calidad",
    "activity": "calibration",
    "frequencyMonths": 12,
    "lastCompletedAt": "2024-10-29",
    "nextDueDate": "2025-10-29",
    "evidenceCount": 1,
    "standard": "Informe de calibración MA22-5144",
    "isReferenceStandard": true,
    "externalProvider": "COMINTEC",
    "measurementType": "Pesos",
    "brand": "ACCURATE",
    "serialNumber": "151816176",
    "measurementRange": "10kg",
    "resolution": "NA",
    "calibrationReport": "MA22-5144",
    "observations": "En tiempo",
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 10
  },
  {
    "id": "standard-pe-tow-007",
    "code": "PE-TOW-007",
    "name": "Pesa paralelepipeda",
    "location": "Calidad",
    "owner": "Calidad",
    "activity": "calibration",
    "frequencyMonths": 12,
    "lastCompletedAt": "2024-10-29",
    "nextDueDate": "2025-10-29",
    "evidenceCount": 1,
    "standard": "Informe de calibración MA22-5144",
    "isReferenceStandard": true,
    "externalProvider": "COMINTEC",
    "measurementType": "Pesos",
    "brand": "ACCURATE",
    "serialNumber": "151916178",
    "measurementRange": "5kg",
    "resolution": "NA",
    "calibrationReport": "MA22-5144",
    "observations": "En tiempo",
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 11
  },
  {
    "id": "standard-tow-lon-01",
    "code": "TOW-LON-01",
    "name": "Regla patron 1 METRO.",
    "location": "Calidad",
    "owner": "Calidad",
    "activity": "calibration",
    "frequencyMonths": 12,
    "lastCompletedAt": "2025-03-22",
    "nextDueDate": "2026-03-22",
    "evidenceCount": 0,
    "standard": "Informe de calibración pendiente",
    "isReferenceStandard": true,
    "externalProvider": "Proveedor pendiente de asignar",
    "measurementType": "Longitud",
    "brand": "KARLEN",
    "serialNumber": "14REGLAS012CH",
    "measurementRange": "1 mm",
    "resolution": "100mm",
    "calibrationReport": "",
    "observations": "En tiempo",
    "sourceDocument": "F-CA-37 Programa de verificación-calibración, Rev. 0",
    "sourceRow": 12
  }
];
